### PR TITLE
Support for higher versions of k8s

### PR DESCRIPTION
**Pull request by molesta98**

### CODE REVIEW

**Comment by molestaShoper** [comment]
Hi
I added support for new versions of kubernetes API and I fixed HPA
Please merge :)

**Comment by molestaShoper** [comment]
@beniamin ping

**Comment by beniamin** [comment]
Sorry for the late response. 
I would like to preserve the support with older k8s versions. Can you add some if/else statements based on k8s versions, in order to preserve the compatibility?

**Comment by molestaShoper** [comment]
@beniamin I added support for older versions 
```
autoscaling:
  enabled: false
  betaApiVersion: false
```

**Comment by beniamin** [comment]
One last request. Please document the use of `betaApiVersion` functionality and mention that it should be enabled for older k8s version

**Review by beniamin — APPROVED** [review]

**Pull request merged**
